spring.application.name=projeto-dever-em-grupo
spring.datasource.url=jdbc:postgresql://localhost:5432/projeto_dever_em_grupo
spring.datasource.username=postgres
spring.datasource.password=aluno
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver